# based on https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
name: Publish Container Image

on:
  release:
    types: [created]

jobs:
  push_to_registry:
    name: Push image to container registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: linuxforhealth/package-test
          releases-only: true
        id: package-test  # The step ID to refer to later.
      - name: QEMU setup
        uses: docker/setup-qemu-action@v2
      - name: Docker buildx setup
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/s390x
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.package-test.outputs.tag }}
